/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DesignJDialog.java
 *
 * Created on Sep 24, 2013, 1:41:22 PM
 */
package com.stitchgalaxy.design_manager;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tarasev
 */
public class DesignJDialog extends javax.swing.JDialog
{

    /** Creates new form DesignJDialog */
    public DesignJDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel26 = new javax.swing.JPanel();
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel27 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel3 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        designUuid = new javax.swing.JTextField();
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel15 = new javax.swing.JPanel();
        lblName1 = new javax.swing.JLabel();
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        releaseDate = new javax.swing.JTextField();
        filler26 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel16 = new javax.swing.JPanel();
        lblName2 = new javax.swing.JLabel();
        filler27 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        priceUsd = new javax.swing.JFormattedTextField();
        filler28 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel17 = new javax.swing.JPanel();
        lblName3 = new javax.swing.JLabel();
        filler29 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        filler30 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel18 = new javax.swing.JPanel();
        lblName4 = new javax.swing.JLabel();
        filler31 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        filler32 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel19 = new javax.swing.JPanel();
        lblName5 = new javax.swing.JLabel();
        filler33 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        filler34 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel20 = new javax.swing.JPanel();
        lblName6 = new javax.swing.JLabel();
        filler35 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        filler36 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel21 = new javax.swing.JPanel();
        lblName7 = new javax.swing.JLabel();
        filler37 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        filler43 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel23 = new javax.swing.JPanel();
        lblName9 = new javax.swing.JLabel();
        filler44 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        filler45 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel24 = new javax.swing.JPanel();
        lblName10 = new javax.swing.JLabel();
        filler46 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        filler47 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel25 = new javax.swing.JPanel();
        lblName11 = new javax.swing.JLabel();
        filler48 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        filler38 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel22 = new javax.swing.JPanel();
        lblName8 = new javax.swing.JLabel();
        filler39 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton1 = new javax.swing.JButton();
        filler40 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel5 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnAddCategory = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnRemoveCategory = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler42 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel10 = new javax.swing.JPanel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnAddCategory1 = new javax.swing.JButton();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnEditLocalization = new javax.swing.JButton();
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnRemoveCategory1 = new javax.swing.JButton();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton2 = new javax.swing.JButton();
        filler22 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jSeparator1 = new javax.swing.JSeparator();
        filler41 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel14 = new javax.swing.JPanel();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnAddCategory2 = new javax.swing.JButton();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler49 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel26.setLayout(new javax.swing.BoxLayout(jPanel26, javax.swing.BoxLayout.LINE_AXIS));
        jPanel26.add(filler20);

        jPanel27.setLayout(new javax.swing.BoxLayout(jPanel27, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel1.add(filler1);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        lblName.setText("Design UUID:");
        lblName.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(lblName);
        jPanel3.add(filler2);

        designUuid.setEditable(false);
        designUuid.setMaximumSize(new java.awt.Dimension(300, 20));
        designUuid.setMinimumSize(new java.awt.Dimension(300, 20));
        designUuid.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(designUuid);

        jPanel1.add(jPanel3);
        jPanel1.add(filler24);

        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        lblName1.setText("Date:");
        lblName1.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName1.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName1.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel15.add(lblName1);
        jPanel15.add(filler25);

        releaseDate.setText("01-01-2013");
        releaseDate.setMaximumSize(new java.awt.Dimension(300, 20));
        releaseDate.setMinimumSize(new java.awt.Dimension(300, 20));
        releaseDate.setPreferredSize(new java.awt.Dimension(300, 20));
        releaseDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                releaseDateKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                releaseDateKeyTyped(evt);
            }
        });
        jPanel15.add(releaseDate);

        jPanel1.add(jPanel15);
        jPanel1.add(filler26);

        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        lblName2.setText("Price USD:");
        lblName2.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName2.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName2.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel16.add(lblName2);
        jPanel16.add(filler27);

        priceUsd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        priceUsd.setMaximumSize(new java.awt.Dimension(300, 20));
        priceUsd.setMinimumSize(new java.awt.Dimension(300, 20));
        priceUsd.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel16.add(priceUsd);

        jPanel1.add(jPanel16);
        jPanel1.add(filler28);

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        lblName3.setText("Sales:");
        lblName3.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName3.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName3.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel17.add(lblName3);
        jPanel17.add(filler29);

        jFormattedTextField3.setText("jFormattedTextField1");
        jFormattedTextField3.setMaximumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField3.setMinimumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField3.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel17.add(jFormattedTextField3);

        jPanel1.add(jPanel17);
        jPanel1.add(filler30);

        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.LINE_AXIS));

        lblName4.setText("Total rating:");
        lblName4.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName4.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName4.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel18.add(lblName4);
        jPanel18.add(filler31);

        jFormattedTextField4.setText("jFormattedTextField1");
        jFormattedTextField4.setMaximumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField4.setMinimumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField4.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel18.add(jFormattedTextField4);

        jPanel1.add(jPanel18);
        jPanel1.add(filler32);

        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.LINE_AXIS));

        lblName5.setText("Total rates:");
        lblName5.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName5.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName5.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel19.add(lblName5);
        jPanel19.add(filler33);

        jFormattedTextField5.setText("jFormattedTextField1");
        jFormattedTextField5.setMaximumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField5.setMinimumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField5.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel19.add(jFormattedTextField5);

        jPanel1.add(jPanel19);
        jPanel1.add(filler34);

        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        lblName6.setText("Avg rating:");
        lblName6.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName6.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName6.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel20.add(lblName6);
        jPanel20.add(filler35);

        jFormattedTextField6.setText("jFormattedTextField1");
        jFormattedTextField6.setMaximumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField6.setMinimumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField6.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel20.add(jFormattedTextField6);

        jPanel1.add(jPanel20);
        jPanel1.add(filler36);

        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.LINE_AXIS));

        lblName7.setText("Colors:");
        lblName7.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName7.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName7.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel21.add(lblName7);
        jPanel21.add(filler37);

        jFormattedTextField7.setText("jFormattedTextField1");
        jFormattedTextField7.setMaximumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField7.setMinimumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField7.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel21.add(jFormattedTextField7);

        jPanel1.add(jPanel21);
        jPanel1.add(filler43);

        jPanel23.setLayout(new javax.swing.BoxLayout(jPanel23, javax.swing.BoxLayout.LINE_AXIS));

        lblName9.setText("Width:");
        lblName9.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName9.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName9.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel23.add(lblName9);
        jPanel23.add(filler44);

        jFormattedTextField8.setText("jFormattedTextField1");
        jFormattedTextField8.setMaximumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField8.setMinimumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField8.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel23.add(jFormattedTextField8);

        jPanel1.add(jPanel23);
        jPanel1.add(filler45);

        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24, javax.swing.BoxLayout.LINE_AXIS));

        lblName10.setText("Height:");
        lblName10.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName10.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName10.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel24.add(lblName10);
        jPanel24.add(filler46);

        jFormattedTextField9.setText("jFormattedTextField1");
        jFormattedTextField9.setMaximumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField9.setMinimumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField9.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel24.add(jFormattedTextField9);

        jPanel1.add(jPanel24);
        jPanel1.add(filler47);

        jPanel25.setLayout(new javax.swing.BoxLayout(jPanel25, javax.swing.BoxLayout.LINE_AXIS));

        lblName11.setText("Complexity:");
        lblName11.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName11.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName11.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel25.add(lblName11);
        jPanel25.add(filler48);

        jFormattedTextField10.setText("jFormattedTextField1");
        jFormattedTextField10.setMaximumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField10.setMinimumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField10.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel25.add(jFormattedTextField10);

        jPanel1.add(jPanel25);
        jPanel1.add(filler38);

        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.LINE_AXIS));

        lblName8.setText("Avg color:");
        lblName8.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName8.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName8.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel22.add(lblName8);
        jPanel22.add(filler39);

        jButton1.setText("jButton1");
        jButton1.setMaximumSize(new java.awt.Dimension(300, 20));
        jButton1.setMinimumSize(new java.awt.Dimension(300, 20));
        jButton1.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel22.add(jButton1);

        jPanel1.add(jPanel22);

        jPanel27.add(jPanel1);
        jPanel27.add(filler40);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Categories:");
        jPanel6.add(jLabel1);
        jPanel6.add(filler9);

        jPanel2.add(jPanel6);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(300, 150));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 150));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 150));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel4.add(jScrollPane1);
        jPanel4.add(filler4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel5.add(filler5);

        btnAddCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jPanel5.add(btnAddCategory);
        jPanel5.add(filler6);

        btnRemoveCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        jPanel5.add(btnRemoveCategory);
        jPanel5.add(filler7);

        jPanel4.add(jPanel5);
        jPanel4.add(filler8);

        jPanel2.add(jPanel4);

        jPanel27.add(jPanel2);
        jPanel27.add(filler42);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Localizations:");
        jPanel8.add(jLabel2);
        jPanel8.add(filler10);

        jPanel7.add(jPanel8);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setMaximumSize(new java.awt.Dimension(300, 200));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(300, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 200));

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel9.add(jScrollPane2);
        jPanel9.add(filler11);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel10.add(filler12);

        btnAddCategory1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jPanel10.add(btnAddCategory1);
        jPanel10.add(filler13);

        btnEditLocalization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jPanel10.add(btnEditLocalization);
        jPanel10.add(filler23);

        btnRemoveCategory1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        jPanel10.add(btnRemoveCategory1);
        jPanel10.add(filler14);

        jPanel9.add(jPanel10);
        jPanel9.add(filler15);

        jPanel7.add(jPanel9);

        jPanel27.add(jPanel7);

        jButton2.setText("Save");
        jPanel27.add(jButton2);
        jPanel27.add(filler22);
        jPanel27.add(jSeparator1);
        jPanel27.add(filler41);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Manage design files:");
        jPanel12.add(jLabel3);
        jPanel12.add(filler16);

        jPanel11.add(jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane3.setMaximumSize(new java.awt.Dimension(300, 150));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(300, 150));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(300, 150));

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jPanel13.add(jScrollPane3);
        jPanel13.add(filler17);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel14.add(filler18);

        btnAddCategory2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jPanel14.add(btnAddCategory2);
        jPanel14.add(filler19);

        jPanel13.add(jPanel14);
        jPanel13.add(filler21);

        jPanel11.add(jPanel13);

        jPanel27.add(jPanel11);

        jPanel26.add(jPanel27);
        jPanel26.add(filler49);

        getContentPane().add(jPanel26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void releaseDateKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_releaseDateKeyTyped
    {//GEN-HEADEREND:event_releaseDateKeyTyped
        
    }//GEN-LAST:event_releaseDateKeyTyped

    private void releaseDateKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_releaseDateKeyReleased
    {//GEN-HEADEREND:event_releaseDateKeyReleased
        DateFormat df = new SimpleDateFormat("MM-dd-yyyy", Locale.ENGLISH);
        try
        {
            String text = releaseDate.getText();
            if (text.length() != 10)
            {
                releaseDate.setText(releaseDatePrevValue);
                return;
            }
            Date result =  df.parse(text);
            releaseDatePrevValue = text;
        }
        catch (ParseException ex)
        {
            releaseDate.setText(releaseDatePrevValue);
        }
    }//GEN-LAST:event_releaseDateKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(DesignJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(DesignJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(DesignJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(DesignJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                DesignJDialog dialog = new DesignJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnAddCategory1;
    private javax.swing.JButton btnAddCategory2;
    private javax.swing.JButton btnEditLocalization;
    private javax.swing.JButton btnRemoveCategory;
    private javax.swing.JButton btnRemoveCategory1;
    private javax.swing.JTextField designUuid;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler22;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler26;
    private javax.swing.Box.Filler filler27;
    private javax.swing.Box.Filler filler28;
    private javax.swing.Box.Filler filler29;
    private javax.swing.Box.Filler filler30;
    private javax.swing.Box.Filler filler31;
    private javax.swing.Box.Filler filler32;
    private javax.swing.Box.Filler filler33;
    private javax.swing.Box.Filler filler34;
    private javax.swing.Box.Filler filler35;
    private javax.swing.Box.Filler filler36;
    private javax.swing.Box.Filler filler37;
    private javax.swing.Box.Filler filler38;
    private javax.swing.Box.Filler filler39;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler40;
    private javax.swing.Box.Filler filler41;
    private javax.swing.Box.Filler filler42;
    private javax.swing.Box.Filler filler43;
    private javax.swing.Box.Filler filler44;
    private javax.swing.Box.Filler filler45;
    private javax.swing.Box.Filler filler46;
    private javax.swing.Box.Filler filler47;
    private javax.swing.Box.Filler filler48;
    private javax.swing.Box.Filler filler49;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName10;
    private javax.swing.JLabel lblName11;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblName8;
    private javax.swing.JLabel lblName9;
    private javax.swing.JFormattedTextField priceUsd;
    private javax.swing.JTextField releaseDate;
    // End of variables declaration//GEN-END:variables

    
    private Design design;
    private boolean  newMode;
    private String releaseDatePrevValue = "01-01-2013";
    
    /**
     * @return the design
     */
    public Design getDesign()
    {
        return design;
    }

    /**
     * @param design the design to set
     */
    public void setDesign(Design design)
    {
        this.design = design;
    }

    /**
     * @return the newMode
     */
    public boolean isNewMode()
    {
        return newMode;
    }

    /**
     * @param newMode the newMode to set
     */
    public void setNewMode(boolean newMode)
    {
        this.newMode = newMode;
    }
    
    
    private void getFormData()
    {
    }
    
    public void setFormData()
    {
        designUuid.setText(design.getDesignUuid().toString());
        priceUsd.setValue(design.getPriceUsd());
    }
}
