/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on Sep 23, 2013, 6:07:52 PM
 */
package com.stitchgalaxy.design_manager;

/**
 *
 * @author tarasev
 */
public class MainForm extends javax.swing.JFrame
{

    /** Creates new form MainForm */
    public MainForm()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDesignGuid = new javax.swing.JLabel();
        ftfDesignGuid = new javax.swing.JFormattedTextField();
        lblDate = new javax.swing.JLabel();
        ftfDate = new javax.swing.JFormattedTextField();
        lblSales = new javax.swing.JLabel();
        ftfSales = new javax.swing.JFormattedTextField();
        lblTotalRates = new javax.swing.JLabel();
        ftfTotalRates = new javax.swing.JFormattedTextField();
        lblTotalRating = new javax.swing.JLabel();
        ftflTotalRating = new javax.swing.JFormattedTextField();
        lblAvgRating = new javax.swing.JLabel();
        ftfRating = new javax.swing.JFormattedTextField();
        lblPriceUsd = new javax.swing.JLabel();
        ftfPriceUsd = new javax.swing.JFormattedTextField();
        lblComplexity = new javax.swing.JLabel();
        ftfComplexity = new javax.swing.JFormattedTextField();
        lblAvgColor = new javax.swing.JLabel();
        btnChoseColor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        btnAddCategory = new javax.swing.JButton();
        btnRemoveCategory = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.GridLayout(9, 2));

        lblDesignGuid.setText("Design UUID:");
        jPanel1.add(lblDesignGuid);

        ftfDesignGuid.setText("jFormattedTextField1");
        jPanel1.add(ftfDesignGuid);

        lblDate.setText("Date:");
        lblDate.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(lblDate);

        ftfDate.setText("jFormattedTextField1");
        jPanel1.add(ftfDate);
        ftfDate.getAccessibleContext().setAccessibleParent(lblDate);

        lblSales.setText("Sales:");
        jPanel1.add(lblSales);

        ftfSales.setText("jFormattedTextField1");
        jPanel1.add(ftfSales);

        lblTotalRates.setText("Total rates:");
        jPanel1.add(lblTotalRates);

        ftfTotalRates.setText("jFormattedTextField1");
        jPanel1.add(ftfTotalRates);

        lblTotalRating.setText("Total rating:");
        jPanel1.add(lblTotalRating);

        ftflTotalRating.setText("jFormattedTextField1");
        jPanel1.add(ftflTotalRating);

        lblAvgRating.setText("Avg rating:");
        jPanel1.add(lblAvgRating);

        ftfRating.setText("jFormattedTextField1");
        jPanel1.add(ftfRating);

        lblPriceUsd.setText("Price USD:");
        jPanel1.add(lblPriceUsd);

        ftfPriceUsd.setText("jFormattedTextField1");
        jPanel1.add(ftfPriceUsd);

        lblComplexity.setText("Complexity:");
        jPanel1.add(lblComplexity);

        ftfComplexity.setText("jFormattedTextField1");
        jPanel1.add(ftfComplexity);

        lblAvgColor.setText("Avg color:");
        jPanel1.add(lblAvgColor);
        jPanel1.add(btnChoseColor);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Categories:");
        jPanel2.add(jLabel1);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setMaximumSize(new java.awt.Dimension(200, 40));
        jList1.setMinimumSize(new java.awt.Dimension(200, 40));
        jList1.setPreferredSize(new java.awt.Dimension(200, 40));
        jScrollPane1.setViewportView(jList1);

        jPanel4.add(jScrollPane1);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        btnAddCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jPanel5.add(btnAddCategory);

        btnRemoveCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        btnRemoveCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCategoryActionPerformed(evt);
            }
        });
        jPanel5.add(btnRemoveCategory);

        jPanel4.add(jPanel5);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveCategoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoveCategoryActionPerformed
    {//GEN-HEADEREND:event_btnRemoveCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveCategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnChoseColor;
    private javax.swing.JButton btnRemoveCategory;
    private javax.swing.JFormattedTextField ftfComplexity;
    private javax.swing.JFormattedTextField ftfDate;
    private javax.swing.JFormattedTextField ftfDesignGuid;
    private javax.swing.JFormattedTextField ftfPriceUsd;
    private javax.swing.JFormattedTextField ftfRating;
    private javax.swing.JFormattedTextField ftfSales;
    private javax.swing.JFormattedTextField ftfTotalRates;
    private javax.swing.JFormattedTextField ftflTotalRating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvgColor;
    private javax.swing.JLabel lblAvgRating;
    private javax.swing.JLabel lblComplexity;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDesignGuid;
    private javax.swing.JLabel lblPriceUsd;
    private javax.swing.JLabel lblSales;
    private javax.swing.JLabel lblTotalRates;
    private javax.swing.JLabel lblTotalRating;
    // End of variables declaration//GEN-END:variables
}
