/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on Sep 23, 2013, 6:07:52 PM
 */
package com.stitchgalaxy.design_manager;

/**
 *
 * @author tarasev
 */
public class MainForm extends javax.swing.JFrame
{

    /** Creates new form MainForm */
    public MainForm()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblDesignGuid = new javax.swing.JLabel();
        ftfDesignGuid = new javax.swing.JFormattedTextField();
        lblDate = new javax.swing.JLabel();
        ftfDate = new javax.swing.JFormattedTextField();
        lblSales = new javax.swing.JLabel();
        ftfSales = new javax.swing.JFormattedTextField();
        lblTotalRates = new javax.swing.JLabel();
        ftfTotalRates = new javax.swing.JFormattedTextField();
        lblTotalRating = new javax.swing.JLabel();
        ftflTotalRating = new javax.swing.JFormattedTextField();
        lblAvgRating = new javax.swing.JLabel();
        ftfRating = new javax.swing.JFormattedTextField();
        lblPriceUsd = new javax.swing.JLabel();
        ftfPriceUsd = new javax.swing.JFormattedTextField();
        lblComplexity = new javax.swing.JLabel();
        ftfComplexity = new javax.swing.JFormattedTextField();
        lblAvgColor = new javax.swing.JLabel();
        btnChoseColor = new javax.swing.JButton();
        pnlCategories = new javax.swing.JPanel();
        lblCategories = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategories = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        btnAddCategory = new javax.swing.JButton();
        btnRemoveCategory = new javax.swing.JButton();
        pnlLocalizations = new javax.swing.JPanel();
        lblLocalizations = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstLocalizations = new javax.swing.JList();
        jPanel8 = new javax.swing.JPanel();
        btnAddLocalization = new javax.swing.JButton();
        btnEditLocalization = new javax.swing.JButton();
        btnRemoveLocalization = new javax.swing.JButton();
        pnlFiles = new javax.swing.JPanel();
        lblFiles = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstFiles = new javax.swing.JList();
        jPanel11 = new javax.swing.JPanel();
        btnAddFile = new javax.swing.JButton();
        btnRemoveFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 1));

        pnlMain.setLayout(new java.awt.GridLayout(9, 2));

        lblDesignGuid.setText("Design UUID:");
        pnlMain.add(lblDesignGuid);

        ftfDesignGuid.setText("jFormattedTextField1");
        pnlMain.add(ftfDesignGuid);

        lblDate.setText("Date:");
        lblDate.setVerifyInputWhenFocusTarget(false);
        pnlMain.add(lblDate);

        ftfDate.setText("jFormattedTextField1");
        pnlMain.add(ftfDate);
        ftfDate.getAccessibleContext().setAccessibleParent(lblDate);

        lblSales.setText("Sales:");
        pnlMain.add(lblSales);

        ftfSales.setText("jFormattedTextField1");
        pnlMain.add(ftfSales);

        lblTotalRates.setText("Total rates:");
        pnlMain.add(lblTotalRates);

        ftfTotalRates.setText("jFormattedTextField1");
        pnlMain.add(ftfTotalRates);

        lblTotalRating.setText("Total rating:");
        pnlMain.add(lblTotalRating);

        ftflTotalRating.setText("jFormattedTextField1");
        pnlMain.add(ftflTotalRating);

        lblAvgRating.setText("Avg rating:");
        pnlMain.add(lblAvgRating);

        ftfRating.setText("jFormattedTextField1");
        pnlMain.add(ftfRating);

        lblPriceUsd.setText("Price USD:");
        pnlMain.add(lblPriceUsd);

        ftfPriceUsd.setText("jFormattedTextField1");
        pnlMain.add(ftfPriceUsd);

        lblComplexity.setText("Complexity:");
        pnlMain.add(lblComplexity);

        ftfComplexity.setText("jFormattedTextField1");
        pnlMain.add(ftfComplexity);

        lblAvgColor.setText("Avg color:");
        pnlMain.add(lblAvgColor);
        pnlMain.add(btnChoseColor);

        getContentPane().add(pnlMain);

        pnlCategories.setLayout(new javax.swing.BoxLayout(pnlCategories, javax.swing.BoxLayout.PAGE_AXIS));

        lblCategories.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCategories.setText("Categories:");
        pnlCategories.add(lblCategories);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        lstCategories.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstCategories.setMaximumSize(new java.awt.Dimension(200, 40));
        lstCategories.setMinimumSize(new java.awt.Dimension(200, 40));
        lstCategories.setPreferredSize(new java.awt.Dimension(200, 40));
        jScrollPane1.setViewportView(lstCategories);

        jPanel4.add(jScrollPane1);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        btnAddCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jPanel5.add(btnAddCategory);

        btnRemoveCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        btnRemoveCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCategoryActionPerformed(evt);
            }
        });
        jPanel5.add(btnRemoveCategory);

        jPanel4.add(jPanel5);

        pnlCategories.add(jPanel4);

        getContentPane().add(pnlCategories);

        pnlLocalizations.setLayout(new javax.swing.BoxLayout(pnlLocalizations, javax.swing.BoxLayout.PAGE_AXIS));

        lblLocalizations.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLocalizations.setText("Localizations:");
        pnlLocalizations.add(lblLocalizations);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        lstLocalizations.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstLocalizations.setMaximumSize(new java.awt.Dimension(200, 40));
        lstLocalizations.setMinimumSize(new java.awt.Dimension(200, 40));
        lstLocalizations.setPreferredSize(new java.awt.Dimension(200, 40));
        jScrollPane2.setViewportView(lstLocalizations);

        jPanel7.add(jScrollPane2);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        btnAddLocalization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jPanel8.add(btnAddLocalization);

        btnEditLocalization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jPanel8.add(btnEditLocalization);

        btnRemoveLocalization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        btnRemoveLocalization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveLocalizationActionPerformed(evt);
            }
        });
        jPanel8.add(btnRemoveLocalization);

        jPanel7.add(jPanel8);

        pnlLocalizations.add(jPanel7);

        getContentPane().add(pnlLocalizations);

        pnlFiles.setLayout(new javax.swing.BoxLayout(pnlFiles, javax.swing.BoxLayout.PAGE_AXIS));

        lblFiles.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFiles.setText("Files:");
        pnlFiles.add(lblFiles);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        lstFiles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstFiles.setMaximumSize(new java.awt.Dimension(200, 40));
        lstFiles.setMinimumSize(new java.awt.Dimension(200, 40));
        lstFiles.setPreferredSize(new java.awt.Dimension(200, 40));
        jScrollPane3.setViewportView(lstFiles);

        jPanel10.add(jScrollPane3);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.PAGE_AXIS));

        btnAddFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jPanel11.add(btnAddFile);

        btnRemoveFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        btnRemoveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFileActionPerformed(evt);
            }
        });
        jPanel11.add(btnRemoveFile);

        jPanel10.add(jPanel11);

        pnlFiles.add(jPanel10);

        getContentPane().add(pnlFiles);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveCategoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoveCategoryActionPerformed
    {//GEN-HEADEREND:event_btnRemoveCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveCategoryActionPerformed

    private void btnRemoveLocalizationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoveLocalizationActionPerformed
    {//GEN-HEADEREND:event_btnRemoveLocalizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveLocalizationActionPerformed

    private void btnRemoveFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoveFileActionPerformed
    {//GEN-HEADEREND:event_btnRemoveFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnAddFile;
    private javax.swing.JButton btnAddLocalization;
    private javax.swing.JButton btnChoseColor;
    private javax.swing.JButton btnEditLocalization;
    private javax.swing.JButton btnRemoveCategory;
    private javax.swing.JButton btnRemoveFile;
    private javax.swing.JButton btnRemoveLocalization;
    private javax.swing.JFormattedTextField ftfComplexity;
    private javax.swing.JFormattedTextField ftfDate;
    private javax.swing.JFormattedTextField ftfDesignGuid;
    private javax.swing.JFormattedTextField ftfPriceUsd;
    private javax.swing.JFormattedTextField ftfRating;
    private javax.swing.JFormattedTextField ftfSales;
    private javax.swing.JFormattedTextField ftfTotalRates;
    private javax.swing.JFormattedTextField ftflTotalRating;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAvgColor;
    private javax.swing.JLabel lblAvgRating;
    private javax.swing.JLabel lblCategories;
    private javax.swing.JLabel lblComplexity;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDesignGuid;
    private javax.swing.JLabel lblFiles;
    private javax.swing.JLabel lblLocalizations;
    private javax.swing.JLabel lblPriceUsd;
    private javax.swing.JLabel lblSales;
    private javax.swing.JLabel lblTotalRates;
    private javax.swing.JLabel lblTotalRating;
    private javax.swing.JList lstCategories;
    private javax.swing.JList lstFiles;
    private javax.swing.JList lstLocalizations;
    private javax.swing.JPanel pnlCategories;
    private javax.swing.JPanel pnlFiles;
    private javax.swing.JPanel pnlLocalizations;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
