/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageLocalizationJDialog.java
 *
 * Created on Sep 24, 2013, 12:29:09 PM
 */
package com.stitchgalaxy.design_manager;

/**
 *
 * @author tarasev
 */
public class ManageLocalizationJDialog extends javax.swing.JDialog
{

    /** Creates new form ManageLocalizationJDialog */
    public ManageLocalizationJDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel3 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jTextField1 = new javax.swing.JTextField();
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel15 = new javax.swing.JPanel();
        lblName1 = new javax.swing.JLabel();
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jTextField2 = new javax.swing.JTextField();
        filler26 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel16 = new javax.swing.JPanel();
        lblName2 = new javax.swing.JLabel();
        filler27 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        filler28 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel17 = new javax.swing.JPanel();
        lblName3 = new javax.swing.JLabel();
        filler29 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jTextField3 = new javax.swing.JTextField();
        filler38 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel5 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnAddCategory = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnRemoveCategory = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler40 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));
        jPanel7.add(filler10);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel1.add(filler1);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        lblName.setText("Language:");
        lblName.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(lblName);
        jPanel3.add(filler2);

        jTextField1.setText("jTextField1");
        jTextField1.setMaximumSize(new java.awt.Dimension(300, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(300, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(jTextField1);

        jPanel1.add(jPanel3);
        jPanel1.add(filler24);

        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        lblName1.setText("Name:");
        lblName1.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName1.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName1.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel15.add(lblName1);
        jPanel15.add(filler25);

        jTextField2.setText("jTextField1");
        jTextField2.setMaximumSize(new java.awt.Dimension(300, 20));
        jTextField2.setMinimumSize(new java.awt.Dimension(300, 20));
        jTextField2.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel15.add(jTextField2);

        jPanel1.add(jPanel15);
        jPanel1.add(filler26);

        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        lblName2.setText("Description:");
        lblName2.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName2.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName2.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel16.add(lblName2);
        jPanel16.add(filler27);

        jFormattedTextField2.setText("jFormattedTextField1");
        jFormattedTextField2.setMaximumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField2.setMinimumSize(new java.awt.Dimension(300, 20));
        jFormattedTextField2.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel16.add(jFormattedTextField2);

        jPanel1.add(jPanel16);
        jPanel1.add(filler28);

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        lblName3.setText("Author:");
        lblName3.setMaximumSize(new java.awt.Dimension(300, 20));
        lblName3.setMinimumSize(new java.awt.Dimension(300, 20));
        lblName3.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel17.add(lblName3);
        jPanel17.add(filler29);

        jTextField3.setText("jTextField1");
        jTextField3.setMaximumSize(new java.awt.Dimension(300, 20));
        jTextField3.setMinimumSize(new java.awt.Dimension(300, 20));
        jTextField3.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel17.add(jTextField3);

        jPanel1.add(jPanel17);
        jPanel1.add(filler38);

        jPanel8.add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Tags:");
        jPanel6.add(jLabel1);
        jPanel6.add(filler9);

        jPanel2.add(jPanel6);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(300, 150));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 150));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 150));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel4.add(jScrollPane1);
        jPanel4.add(filler4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel5.add(filler5);

        btnAddCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jPanel5.add(btnAddCategory);
        jPanel5.add(filler6);

        btnRemoveCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        btnRemoveCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCategoryActionPerformed(evt);
            }
        });
        jPanel5.add(btnRemoveCategory);
        jPanel5.add(filler7);

        jPanel4.add(jPanel5);
        jPanel4.add(filler8);

        jPanel2.add(jPanel4);

        jPanel8.add(jPanel2);
        jPanel8.add(filler40);

        jPanel7.add(jPanel8);
        jPanel7.add(filler11);

        getContentPane().add(jPanel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveCategoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoveCategoryActionPerformed
    {//GEN-HEADEREND:event_btnRemoveCategoryActionPerformed

    }//GEN-LAST:event_btnRemoveCategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }



        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ManageLocalizationJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ManageLocalizationJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ManageLocalizationJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ManageLocalizationJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                ManageLocalizationJDialog dialog = new ManageLocalizationJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnRemoveCategory;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler26;
    private javax.swing.Box.Filler filler27;
    private javax.swing.Box.Filler filler28;
    private javax.swing.Box.Filler filler29;
    private javax.swing.Box.Filler filler38;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler40;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    // End of variables declaration//GEN-END:variables
}
