[
uuid(4f6ec108-5779-40ab-bbf9-bf60e35e6198),
pointer_default(unique),
version(1.0)
]
interface MCXFeedService_Int
{
	int MCXFeedService_GetServiceState([in, out, ref, size_is(nSize)] byte* pStatus, [in] int nSize);
	int MCXFeedService_PutJobRequest([in, out, ref, size_is(nSize)] byte* pRequest, [in] int nSize);
	int MCXFeedService_GetConfig([in, out, ref, size_is(nSize)] byte* pRequest, [in] int nSize);
	int MCXFeedService_SetConfig([in, out, ref, size_is(nSize)] byte* pRequest, [in] int nSize);
	int MCXFeedService_GetSecList([in, out, ref, size_is(nSize)] byte* pList, [in] int nSize);
	int MCXFeedService_GetLogList([in, out, ref, size_is(nSize)] byte* pList, [in] int nSize, [in] __int64 nLastRec);
}
